#
# Labtainer Dockerfile
#
#  This is the default Labtainer Dockerfile template, please choose the appropriate
#  base image below.
#
ARG registry
FROM $registry/labtainer.base2
#FROM $registry/labtainer.network
#FROM $registry/labtainer.centos
#FROM $registry/labtainer.lamp
#
ARG lab
ARG labdir
ARG imagedir
ARG user_name
ARG password
ARG apt_source
ARG version
LABEL version=$version
ENV APT_SOURCE $apt_source
RUN /usr/bin/apt-source.sh
#
# Install the system files found in the _system directory
#
ADD $labdir/$imagedir/sys_tar/sys.tar /
ADD $labdir/sys_$lab.tar.gz /
#
RUN useradd -ms /bin/bash $user_name
RUN echo "$user_name:$password" | chpasswd
RUN adduser $user_name sudo
#
# Perform all root operations, e.g., "apt-get install" prior to the USER command.
#
USER root
# Install necessary packages
RUN apt-get update && \
    apt-get install -y --no-install-recommends apache2 php php-xml php-mbstring wget curl firefox nmap openssh-server && \
    service apache2 restart && \
    wget https://codeload.github.com/rapid7/metasploit-framework/tar.gz/refs/tags/5.0.100 -O metasploit-framework-5.0.100.tar.gz && \
    tar -xzvf metasploit-framework-5.0.100.tar.gz && \
    mv metasploit-framework-5.0.100 /home && \
    chmod 777  /home/metasploit-framework-5.0.100 && \
    chown 777 /home/metasploit-framework-5.0.100 && \
    cd /home/metasploit-framework-5.0.100 && \
    apt install git curl autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm6 libgdbm-dev libdb-dev -y && \
    apt install ruby-full -y && \
    apt-get install gem -y && \
    gem install bundler:1.17.3 && \
    apt-get install zlib1g-dev -y && \
    apt-get install libpq-dev -y && \
    apt-get install libpcap-dev -y && \
    apt-get install libsqlite3-dev -y && \
    sudo bundler install && \
    apt-get install -y --no-install-recommends apache2 php php-xml php-mbstring wget curl build-essential tcl dirb && \
    wget https://download.redis.io/releases/redis-5.0.7.tar.gz && \
    tar -xvzf redis-5.0.7.tar.gz && \
    cd redis-5.0.7 && \
    make && \
    make install && \
    mkdir -p /etc/redis /var/lib/redis && \
    cp redis.conf /etc/redis/redis.conf && \
    sed -i 's/^supervised no/supervised systemd/' /etc/redis/redis.conf && \
    sed -i 's|^dir ./|dir /var/lib/redis|' /etc/redis/redis.conf && \
    echo -e "[Unit]\nDescription=Redis In-Memory Data Store\nAfter=network.target\n\n[Service]\nUser=root\nGroup=root\nExecStart=/usr/local/bin/redis-server /etc/redis/redis.conf\nExecStop=/usr/local/bin/redis-cli shutdown\nRestart=always\n\n[Install]\nWantedBy=multi-user.target" | sudo tee /etc/systemd/system/redis.service > /dev/null && \
    sed -i 's/^bind 127.0.0.1/bind 0.0.0.0/' /etc/redis/redis.conf && \
    sed -i 's/^protected-mode yes/protected-mode no/' /etc/redis/redis.conf && \
    echo -e '#!/bin/bash\nredis-server /etc/redis/redis.conf' > /etc/init.d/redis && \
    chmod +x /etc/init.d/redis && \
    ln -s /etc/init.d/redis /etc/rc3.d/S99redis



# Thêm file vào container

USER $user_name
ENV HOME /home/$user_name
ADD $labdir/$imagedir/home_tar/home.tar $HOME
RUN rm -f $HOME/home.tar
ADD $labdir/$lab.tar.gz $HOME





USER root
WORKDIR /home/ubuntu

# Start Apache in the foreground
CMD ["/bin/bash", "-c", "service ssh start && service redis start && apachectl -D FOREGROUND"]
RUN echo 'export PATH=$PATH:/home/metasploit-framework-5.0.100' >> ~/.bashrc && \
    echo "source ~/.bashrc" >> ~/.bash_profile

