# Labtainer Dockerfile
ARG registry
FROM $registry/labtainer.base2

# Thông tin và cài đặt ban đầu
ARG lab
ARG labdir
ARG imagedir
ARG user_name
ARG password
ARG apt_source
ARG version
LABEL version=$version
ENV APT_SOURCE $apt_source
RUN /usr/bin/apt-source.sh

# Cài đặt Redis
RUN apt-get update && \
    apt-get install -y --no-install-recommends apache2 php php-xml php-mbstring wget curl build-essential tcl dirb && \
    wget https://download.redis.io/releases/redis-5.0.7.tar.gz && \
    tar -xvzf redis-5.0.7.tar.gz && \
    cd redis-5.0.7 && \
    make && \
    make install && \
    mkdir -p /etc/redis /var/lib/redis && \
    cp redis.conf /etc/redis/redis.conf && \
    sed -i 's/^supervised no/supervised systemd/' /etc/redis/redis.conf && \
    sed -i 's|^dir ./|dir /var/lib/redis|' /etc/redis/redis.conf && \
    echo -e "[Unit]\nDescription=Redis In-Memory Data Store\nAfter=network.target\n\n[Service]\nUser=root\nGroup=root\nExecStart=/usr/local/bin/redis-server /etc/redis/redis.conf\nExecStop=/usr/local/bin/redis-cli shutdown\nRestart=always\n\n[Install]\nWantedBy=multi-user.target" | sudo tee /etc/systemd/system/redis.service > /dev/null && \
    sed -i 's/^bind 127.0.0.1/bind 0.0.0.0/' /etc/redis/redis.conf && \
    sed -i 's/^protected-mode yes/protected-mode no/' /etc/redis/redis.conf && \
    echo -e '#!/bin/bash\nredis-server /etc/redis/redis.conf' > /etc/init.d/redis && \
    chmod +x /etc/init.d/redis && \
    ln -s /etc/init.d/redis /etc/rc3.d/S99redis

# Cấu hình người dùng
RUN useradd -ms /bin/bash $user_name && \
    echo "$user_name:$password" | chpasswd && \
    adduser $user_name sudo

# Thêm file vào container
ADD $labdir/$imagedir/sys_tar/sys.tar /
ADD $labdir/sys_$lab.tar.gz /
USER $user_name
ENV HOME /home/$user_name
ADD $labdir/$imagedir/home_tar/home.tar $HOME
RUN rm -f $HOME/home.tar
ADD $labdir/$lab.tar.gz $HOME
USER root

# Chạy dịch vụ Redis và Apache khi container khởi động
CMD ["/bin/bash", "-c", "service redis start && apachectl -D FOREGROUND"]


